name: Deploy to Azure

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.8'

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            # Ici des étapes pour packager et préparer le déploiement

            - name: Deploy to Azure Web App
              env:
                  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
                  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
              run: |
                  echo "Déploiement de l'application sur Azure..."
                  # Commande Azure CLI pour déployer
                  az webapp up --name $AZURE_WEBAPP_NAME --sku F1 --location "West Europe"
