name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 :
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Étape 3 : Login to ACR
      - name: Login to ACR
        run: |
          az acr login --name ${{ secrets.ACR_NAME }}

      # Étape 4 : Build Docker image locally
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/sentiment-analysis:latest .

      # Étape 5 : Push Docker image to ACR
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.ACR_NAME }}.azurecr.io/sentiment-analysis:latest

      # Étape 6 : Configure App Service to use the Docker image
      - name: Deploy Image to Web App
        run: |
          az webapp config container set \
            --name ${{ secrets.APP_SERVICE_NAME }} \
            --resource-group SentimentAnalysisGroup \
            --docker-custom-image-name ${{ secrets.ACR_NAME }}.azurecr.io/sentiment-analysis:latest \
            --docker-registry-server-url https://${{ secrets.ACR_NAME }}.azurecr.io \
            --docker-registry-server-user ${{ secrets.AZURE_CREDENTIALS.CLIENT_ID }} \
            --docker-registry-server-password ${{ secrets.AZURE_CREDENTIALS.CLIENT_SECRET }}
