name: Deploy to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Vérifier le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Connexion à Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Construire et pousser l'image Docker sur ACR
      - name: Build and Push Docker Image
        run: |
          az acr build --registry ${{ secrets.ACR_NAME }} \
            --image ${{ secrets.ACR_NAME }}/sentiment-analysis:latest .

      # Déployer l'image sur App Service
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.APP_SERVICE_NAME }}
          slot-name: production
          images: ${{ secrets.ACR_NAME }}/sentiment-analysis:latest
